"""Canonical reason codes. Used in headers, receipts, events, logs and the UI."""
from enum import Enum


class Reason(str, Enum):
    CACHE_VERIFIED = "CACHE_VERIFIED"
    CACHE_HARD_NEGATIVE = "CACHE_HARD_NEGATIVE"
    CACHE_NAMESPACE_MISMATCH = "CACHE_NAMESPACE_MISMATCH"
    CACHE_STALE = "CACHE_STALE"
    CACHE_CONTEXT_MISMATCH = "CACHE_CONTEXT_MISMATCH"
    CACHE_SOURCE_REVOKED = "CACHE_SOURCE_REVOKED"
    CACHE_MISS = "CACHE_MISS"
    CACHE_INELIGIBLE = "CACHE_INELIGIBLE"
    LOCAL_CONFIDENT = "LOCAL_CONFIDENT"
    LOCAL_LARGE_SELECTED = "LOCAL_LARGE_SELECTED"
    REMOTE_ALLOWED = "REMOTE_ALLOWED"
    REMOTE_DISABLED = "REMOTE_DISABLED"
    REMOTE_UNAVAILABLE = "REMOTE_UNAVAILABLE"
    SENSITIVE_LOCAL_ONLY = "SENSITIVE_LOCAL_ONLY"
    SECRET_BLOCKED = "SECRET_BLOCKED"
    BUDGET_DENY = "BUDGET_DENY"
    POLICY_BLOCK = "POLICY_BLOCK"
    ROUTER_ABSTAIN = "ROUTER_ABSTAIN"
    ROUTER_UNAVAILABLE = "ROUTER_UNAVAILABLE"
    ROUTER_POST_HOC_STREAM = "ROUTER_POST_HOC_STREAM"
    CONNECTOR_UNAVAILABLE = "CONNECTOR_UNAVAILABLE"
    DLP_UNAVAILABLE_FAIL_CLOSED = "DLP_UNAVAILABLE_FAIL_CLOSED"
    PII_REDACTED = "PII_REDACTED"
    OUTPUT_BLOCKED = "OUTPUT_BLOCKED"
    OUTPUT_REDACTED = "OUTPUT_REDACTED"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    RATE_LIMITED = "RATE_LIMITED"
    QUEUE_FULL = "QUEUE_FULL"
    INPUT_TOO_LARGE = "INPUT_TOO_LARGE"
    TENANT_SPOOF_REJECTED = "TENANT_SPOOF_REJECTED"
    DEPARTMENT_SPOOF_REJECTED = "DEPARTMENT_SPOOF_REJECTED"
    AUTH_INVALID = "AUTH_INVALID"
    AUTH_REVOKED = "AUTH_REVOKED"
    AUTH_EXPIRED = "AUTH_EXPIRED"
    SCOPE_DENIED = "SCOPE_DENIED"
    ROUTE_ESCALATION_DENIED = "ROUTE_ESCALATION_DENIED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


# Primary-reason precedence: earlier = more salient for the headline reason of a receipt.
PRECEDENCE = [
    Reason.TENANT_SPOOF_REJECTED, Reason.DEPARTMENT_SPOOF_REJECTED, Reason.AUTH_INVALID, Reason.AUTH_REVOKED,
    Reason.AUTH_EXPIRED, Reason.SCOPE_DENIED, Reason.RATE_LIMITED, Reason.QUEUE_FULL, Reason.INPUT_TOO_LARGE,
    Reason.DLP_UNAVAILABLE_FAIL_CLOSED, Reason.SECRET_BLOCKED, Reason.POLICY_BLOCK, Reason.ROUTE_ESCALATION_DENIED,
    Reason.BUDGET_DENY, Reason.MODEL_UNAVAILABLE, Reason.OUTPUT_BLOCKED, Reason.CACHE_VERIFIED,
    Reason.SENSITIVE_LOCAL_ONLY, Reason.CACHE_HARD_NEGATIVE, Reason.CONNECTOR_UNAVAILABLE,
    Reason.REMOTE_UNAVAILABLE, Reason.ROUTER_ABSTAIN, Reason.LOCAL_LARGE_SELECTED, Reason.REMOTE_ALLOWED,
    Reason.ROUTER_POST_HOC_STREAM, Reason.CACHE_STALE, Reason.CACHE_SOURCE_REVOKED, Reason.CACHE_CONTEXT_MISMATCH,
    Reason.OUTPUT_REDACTED, Reason.PII_REDACTED, Reason.LOCAL_CONFIDENT, Reason.ROUTER_UNAVAILABLE,
    Reason.REMOTE_DISABLED, Reason.CACHE_NAMESPACE_MISMATCH, Reason.CACHE_MISS, Reason.CACHE_INELIGIBLE,
]


def primary(codes: list[str]) -> str:
    order = {r.value: i for i, r in enumerate(PRECEDENCE)}
    return min(codes, key=lambda c: order.get(c, 999)) if codes else ""
